### ISSUE TITLE
[compatibility] player join/quit/death event

### ISSUE THREAD

**Issue by user127001** [MrBrikster/Chatty#42]
Hello!
When the Chatty plugin is installed, all messages about the player’s join/quit/death, including messages from other plugins (for example, DeathMessagesPrime) are blocked if
```
misc:
  join/quit/death:
    message: ''
```
or overwritten if
```
misc:
  join/quit/death:
    message: 'anything'
```

I ask you to add an option to the config, which would allow you to completely disable listening to the join/quit/death events.
Best regards.

**Comment by MrBrikster** [comment]
Hello!

You can just remove "join/quit/death" block from "misc" section and events won't be blocked.

For example, if you need change "join" and "quit" messages, but don't want block death messages, you can write this lines (without death block):
`misc:
  join:
    message: '&e{prefix}{player}{suffix} &ejoined the server.'
    permission: false
  quit:
    permission: false`

**Comment by user127001** [comment]
Thanks a lot! It working now!
